Misc metadata updates
spacetelescope/ullyses-utils pull request #116
Opened 2023-11-26 19:44 UTC by jotaylor

- Remove bad SZ102 visit D9 from STIS config.
- Add bad SZ102 visit D9 to rejected list, add bad V-BP-TAU exposure to rejected list
- Add quality comments for datasets with high CR rates, DQ=2048 removed, vignetting flagged, and stisblazefix applied
- Rename V-V1154-SCO-A back to V-V1154-SCO
- Update spectral type of cvso-104

2023-11-26 19:47 UTC, jotaylor commented
Woops, I need to add the updated calibration DB, so marking this as a draft for now

2023-11-27 18:11 UTC, Rplesha requested changes
Small update to the readme, but otherwise looks good.

2023-11-27 18:11 UTC, Rplesha commented on README.md
> +match_aliases("BAT99 105")
I think I would add here the different columns that are available to specify. I think I added this in the docstring so you might be able to copy/paste

2023-11-27 18:37 UTC, Rplesha submitted a review, later dismissed
Perfect!

2023-11-27 18:38 UTC, jotaylor commented
@Rplesha I see there is a conflict for the Cal DB, unsurprisingly. I tried resolving it myself but there are many conflicting rows due to the number of quality comments I added. Do you think I should just scrap the updates to the DB here, merge the branch, then create a new branch with DB updates after I run the creation script?

2023-11-27 18:44 UTC, Rplesha commented
@jotaylor I find it easiest to merge main into the current branch and run everything again if you want to give that a go. I think that should resolve the conflicts...potentially.

2023-11-27 20:54 UTC, Rplesha approved these changes

2023-11-27 20:56 UTC, merged